# exampleSite/config.yaml
baseURL: https://uhnari.xyz/ # Replace with your domain
languageCode: en-us
theme: smigle
title: Uhnari
summaryLength: 50

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1 

# CONTENT
    - identifier: archive
      name: Archive
      url: /posts/
      weight: 4

    - identifier: stories
      name: Stories
      url: /categories/stories/
      weight: 2

    - identifier: articles
      name: Articles
      url: /categories/articles
      weight: 3 

    - identifier:
      name:
      url:
      weight:

#PROFFESIONAL
    - identifier: services
      name: Services
      url: /services/
      weight: 7
    - identifier: about
      name: About/Contact
      url: /about/
      weight: 6

#SEARCH
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 8
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 9
params:
  abbrDateFmt: "Jan 02"
  author: "Uhnari"
  brandIconFile: "images/profile.gif"
  dateFmt: "Monday, 2006-01-02"
#  customStylesheets: # Use to override theme styles, like logo size
#    - "css/custom.css"
  social:
    - name: Patreon
      url: https://www.patreon.com/uhnari
    - name: Critique Circle
      url: https://www.critiquecircle.com/u/Uhnari
    - name:
      url:
  subtitle: "Freelance Writer and Novelist"  
