# exampleSite/config.yaml
baseURL: https://uhnari.netlify.app/ # Replace with your domain
languageCode: en-us
theme: smigle
title: Uhnari
summaryLength: 100

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1 

# CONTENT
    - identifier: archive
      name: Archive
      url: /posts/
      weight: 3

    - identifier: aether series
      name: Aether Series
      url: /categories/aetherseries/
      weight: 2

#PROFFESIONAL
    - identifier: services
      name: Services
      url: /services/
      weight: 7

    - identifier: about
      name: About / Contact
      url: /about/
      weight: 8

#SEARCH
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 5
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 6
params:
  abbrDateFmt: "Jan 02"
  author: "Robert Uhnari"
  brandIconFile: "images/profile.gif"
  dateFmt: "Monday, 2006-01-02"
  subtitle: "Freelance Writer, Aspiring Novelist."
  ##
  ## Options for overriding theme or page defaults
  ##
  #customStylesheets: # Use to override theme styles, like logo size
  #  - "css/custom.css"
  #readingSpeed: 600 # Use to set custom reading speed
  #readingSpeedMin: 25 # Use to set custom reading speed range
  #readingSpeedMax: 175 # Use to set custom reading speed range

  social:
    - name: Patreon
      url: https://www.patreon.com/uhnari
    - name: Critique Circle
      url: https://www.critiquecircle.com/u/Uhnari
    - name:
      url:  
